# Site settings
name: Diptamay Sanyal
email: me@diptamay.com
#canonical_url: https://edwinexemplar.com
keywords: "Java, Scala, Akka, Golang, AI, Machine Learning, Startups, Aerospike, Node.js, Vert.x, Spring, gRPC, REST, Spark, Kafka, Airflow, Metabase, Bigquery, Databricks, LlamaIndex, Chroma, ElasticSearch, DynamoDB, Redis, SQS, EC2, EMR, ECS, Pubsub, App Engine"
skills: "Technical Lead | Architect | Data | AI | Cloud, NJ/NYC Metro Area"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/diptamay/
#  - title: medium
#    url: https://medium.com/@diptamay
#  - title: twitter
#    url: https://twitter.com/diptamay
  - title: github
    url: https://github.com/diptamay

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
